// <auto-generated />
namespace SBMSystemMVCApp.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class supplier_table_added1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(supplier_table_added1));
        
        string IMigrationMetadata.Id
        {
            get { return "201907301042229_supplier_table_added1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
